version: '3.8'

services:
  db:
    image: postgres:14
    container_name: notekeeper-postgres
    environment:
      POSTGRES_DB: notekeeperdb
      POSTGRES_USER: notekeeper
      POSTGRES_PASSWORD: note12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: notekeeper-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notekeeperdb
      SPRING_DATASOURCE_USERNAME: notekeeper
      SPRING_DATASOURCE_PASSWORD: note12345
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
